import { NodeCategory } from '@/stores/workflowStore';

export interface NodeUsageGuide {
  overview: string;
  inputs: string[];
  outputs: string[];
  example: string;
  tips?: string[];
}

export interface NodeTypeDefinition {
  type: string;
  label: string;
  category: NodeCategory;
  icon: string;
  description: string;
  defaultConfig: Record<string, unknown>;
  configFields: ConfigField[];
  usageGuide?: NodeUsageGuide;
}

export interface ConfigField {
  key: string;
  label: string;
  type: 'text' | 'textarea' | 'number' | 'select' | 'boolean' | 'json' | 'cron' | 'time';
  placeholder?: string;
  options?: { label: string; value: string }[];
  required?: boolean;
  defaultValue?: unknown;
  helpText?: string;
}

export const NODE_CATEGORIES: { id: NodeCategory; label: string; color: string }[] = [
  { id: 'triggers', label: 'Trigger Nodes', color: 'hsl(var(--primary))' },
  { id: 'logic', label: 'Core Logic Nodes', color: 'hsl(var(--secondary))' },
  { id: 'data', label: 'Data Manipulation', color: 'hsl(142 71% 45%)' },
  { id: 'database', label: 'Database Nodes', color: 'hsl(217 91% 60%)' },
  { id: 'storage', label: 'File & Storage Nodes', color: 'hsl(262 83% 58%)' },
  { id: 'ai', label: 'AI & ML Nodes', color: 'hsl(var(--accent))' },
  { id: 'http_api', label: 'HTTP & API', color: 'hsl(221 83% 53%)' },
  { id: 'output', label: 'Output/Communication', color: 'hsl(25 95% 53%)' },
  { id: 'google', label: 'Google Nodes', color: 'hsl(217 89% 61%)' },
];

export const NODE_TYPES: NodeTypeDefinition[] = [
  // ============================================
  // 1. TRIGGER NODES (8/8)
  // ============================================
  {
    type: 'manual_trigger',
    label: 'Manual Trigger',
    category: 'triggers',
    icon: 'Play',
    description: 'Start workflow manually for testing and debugging',
    defaultConfig: {},
    configFields: [],
  },
  {
    type: 'schedule',
    label: 'Schedule Trigger (Cron)',
    category: 'triggers',
    icon: 'Clock',
    description: 'Execute workflows based on cron schedules',
    defaultConfig: { time: '09:00', timezone: 'Asia/Kolkata' },
    configFields: [
      { 
        key: 'time', 
        label: 'Time (HH:MM)', 
        type: 'time', 
        placeholder: '09:00', 
        defaultValue: '09:00',
        required: true, 
        helpText: 'Time in 24-hour format (e.g., 09:00 for 9 AM, 14:30 for 2:30 PM)' 
      },
      { 
        key: 'timezone', 
        label: 'Timezone', 
        type: 'select', 
        options: [
          { label: 'Indian Standard Time (IST)', value: 'Asia/Kolkata' },
          { label: 'UTC (Coordinated Universal Time)', value: 'UTC' },
          { label: 'Eastern Time (US)', value: 'America/New_York' },
          { label: 'Central Time (US)', value: 'America/Chicago' },
          { label: 'Mountain Time (US)', value: 'America/Denver' },
          { label: 'Pacific Time (US)', value: 'America/Los_Angeles' },
          { label: 'London (GMT/BST)', value: 'Europe/London' },
          { label: 'Paris (CET/CEST)', value: 'Europe/Paris' },
          { label: 'Berlin (CET/CEST)', value: 'Europe/Berlin' },
          { label: 'Tokyo (JST)', value: 'Asia/Tokyo' },
          { label: 'Shanghai (CST)', value: 'Asia/Shanghai' },
          { label: 'Singapore (SGT)', value: 'Asia/Singapore' },
          { label: 'Sydney (AEDT/AEST)', value: 'Australia/Sydney' },
          { label: 'Melbourne (AEDT/AEST)', value: 'Australia/Melbourne' },
          { label: 'Dubai (GST)', value: 'Asia/Dubai' },
          { label: 'Mumbai (IST)', value: 'Asia/Kolkata' },
          { label: 'New Delhi (IST)', value: 'Asia/Kolkata' },
          { label: 'Bangalore (IST)', value: 'Asia/Kolkata' },
        ],
        defaultValue: 'Asia/Kolkata',
        required: true, 
        helpText: 'Select your timezone for schedule execution' 
      },
    ],
  },
  {
    type: 'webhook',
    label: 'Webhook',
    category: 'triggers',
    icon: 'Webhook',
    description: 'Trigger workflow from HTTP requests',
    defaultConfig: { method: 'POST' },
    configFields: [
      { key: 'method', label: 'Method', type: 'select', options: [
        { label: 'GET', value: 'GET' },
        { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' },
      ], defaultValue: 'POST', required: true },
    ],
  },
  {
    type: 'chat_trigger',
    label: 'Chat Trigger',
    category: 'triggers',
    icon: 'MessageSquare',
    description: 'Trigger workflow from chat / AI / UI messages',
    defaultConfig: {},
    configFields: [],
  },
  {
    type: 'error_trigger',
    label: 'Error Trigger',
    category: 'triggers',
    icon: 'ShieldAlert',
    description: 'Automatically fire when any node fails',
    defaultConfig: {},
    configFields: [],
  },
  {
    type: 'interval',
    label: 'Interval',
    category: 'triggers',
    icon: 'Timer',
    description: 'Run workflow repeatedly at fixed intervals',
    defaultConfig: { interval: '10m' },
    configFields: [
      { key: 'interval', label: 'Interval', type: 'text', placeholder: '10m', required: true, helpText: 'Interval in seconds (s), minutes (m), or hours (h). Examples: 30s, 5m, 1h' },
    ],
  },
  {
    type: 'workflow_trigger',
    label: 'Workflow Trigger',
    category: 'triggers',
    icon: 'Link',
    description: 'Trigger one workflow from another workflow',
    defaultConfig: { source_workflow_id: '' },
    configFields: [
      { key: 'source_workflow_id', label: 'Source Workflow ID', type: 'text', placeholder: '', required: true, helpText: 'ID of the workflow that will trigger this workflow' },
    ],
  },

  // ============================================
  // 2. CORE LOGIC NODES (10/10)
  // ============================================
  {
    type: 'if_else',
    label: 'If/Else',
    category: 'logic',
    icon: 'GitBranch',
    description: 'Conditional branching',
    defaultConfig: { condition: '' },
    configFields: [
      { key: 'condition', label: 'Condition', type: 'text', placeholder: '{{input.value}} > 10', required: true },
    ],
  },
  {
    type: 'switch',
    label: 'Switch',
    category: 'logic',
    icon: 'GitMerge',
    description: 'Multiple case branching',
    defaultConfig: { cases: [] },
    configFields: [
      { key: 'expression', label: 'Expression', type: 'text', placeholder: '{{input.status}}', required: true },
      { key: 'cases', label: 'Cases (JSON)', type: 'json', placeholder: '[{"value": "active", "label": "Active"}]' },
    ],
  },
  {
    type: 'merge',
    label: 'Merge',
    category: 'logic',
    icon: 'GitMerge',
    description: 'Merge multiple inputs with different strategies',
    defaultConfig: { mode: 'merge' },
    configFields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [
        { label: 'Merge Objects', value: 'merge' },
        { label: 'Append to Array', value: 'append' },
        { label: 'Key-based Merge', value: 'key_based' },
        { label: 'Wait All', value: 'wait_all' },
        { label: 'Concatenate Arrays', value: 'concat' },
      ], defaultValue: 'merge' },
      { key: 'mergeKey', label: 'Merge Key', type: 'text', placeholder: 'id', helpText: 'For key-based merge mode' },
    ],
  },
  {
    type: 'loop',
    label: 'Loop',
    category: 'logic',
    icon: 'Repeat',
    description: 'Iterate over items',
    defaultConfig: { maxIterations: 100 },
    configFields: [
      { key: 'array', label: 'Array Expression', type: 'text', placeholder: '{{input.items}}', required: true },
      { key: 'maxIterations', label: 'Max Iterations', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'wait',
    label: 'Wait/Delay',
    category: 'logic',
    icon: 'Timer',
    description: 'Pause execution',
    defaultConfig: { duration: 1000 },
    configFields: [
      { key: 'duration', label: 'Duration (ms)', type: 'number', defaultValue: 1000, required: true },
    ],
  },
  {
    type: 'error_handler',
    label: 'Error Handler',
    category: 'logic',
    icon: 'ShieldAlert',
    description: 'Handle errors gracefully',
    defaultConfig: { retries: 3, retryDelay: 1000 },
    configFields: [
      { key: 'retries', label: 'Max Retries', type: 'number', defaultValue: 3 },
      { key: 'retryDelay', label: 'Retry Delay (ms)', type: 'number', defaultValue: 1000 },
      { key: 'fallbackValue', label: 'Fallback Value', type: 'json', placeholder: 'null' },
    ],
  },
  {
    type: 'filter',
    label: 'Filter',
    category: 'logic',
    icon: 'Filter',
    description: 'Filter array items',
    defaultConfig: { condition: '' },
    configFields: [
      { key: 'array', label: 'Array Expression', type: 'text', placeholder: '{{input.items}}', required: true },
      { key: 'condition', label: 'Filter Condition', type: 'text', placeholder: 'item.active === true', required: true },
    ],
  },
  {
    type: 'noop',
    label: 'NoOp (Pass Through)',
    category: 'logic',
    icon: 'Box',
    description: 'Pass input through unchanged (no operation)',
    defaultConfig: {},
    configFields: [],
  },
  {
    type: 'stop_and_error',
    label: 'Stop And Error',
    category: 'logic',
    icon: 'XCircle',
    description: 'Stop workflow execution and trigger error',
    defaultConfig: { errorMessage: 'Workflow stopped', errorCode: 'STOPPED' },
    configFields: [
      { key: 'errorMessage', label: 'Error Message', type: 'text', placeholder: 'Workflow stopped', required: true },
      { key: 'errorCode', label: 'Error Code', type: 'text', placeholder: 'STOPPED' },
    ],
  },
  {
    type: 'split_in_batches',
    label: 'Split In Batches',
    category: 'logic',
    icon: 'Layers',
    description: 'Split array into batches',
    defaultConfig: { batchSize: 10 },
    configFields: [
      { key: 'array', label: 'Array Expression', type: 'text', placeholder: '{{input.items}}', required: true },
      { key: 'batchSize', label: 'Batch Size', type: 'number', defaultValue: 10, required: true },
    ],
  },

  // ============================================
  // 3. DATA MANIPULATION NODES (13/13)
  // ============================================
  {
    type: 'set',
    label: 'Set',
    category: 'data',
    icon: 'Edit',
    description: 'Set field values in object',
    defaultConfig: { fields: '{}' },
    configFields: [
      { key: 'fields', label: 'Fields (JSON)', type: 'json', placeholder: '{"name": "{{input.name}}", "age": 25}', required: true, helpText: 'JSON object with field names and values (supports templates)' },
    ],
  },
  {
    type: 'edit_fields',
    label: 'Edit Fields',
    category: 'data',
    icon: 'Edit3',
    description: 'Edit fields with operations (set, delete, rename)',
    defaultConfig: { operations: '[]' },
    configFields: [
      { key: 'operations', label: 'Operations (JSON)', type: 'json', placeholder: '[{"operation": "set", "field": "name", "value": "John"}]', required: true, helpText: 'Array of operations: set, delete, rename' },
    ],
  },
  {
    type: 'rename_keys',
    label: 'Rename Keys',
    category: 'data',
    icon: 'Tag',
    description: 'Rename object keys',
    defaultConfig: { mappings: '{}' },
    configFields: [
      { key: 'mappings', label: 'Key Mappings (JSON)', type: 'json', placeholder: '{"oldName": "newName"}', required: true, helpText: 'JSON object mapping old keys to new keys' },
    ],
  },
  {
    type: 'aggregate',
    label: 'Aggregate',
    category: 'data',
    icon: 'Code2',
    description: 'Aggregate operations on arrays (sum, avg, count, min, max)',
    defaultConfig: { operation: 'sum' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Sum', value: 'sum' },
        { label: 'Average', value: 'avg' },
        { label: 'Count', value: 'count' },
        { label: 'Min', value: 'min' },
        { label: 'Max', value: 'max' },
      ], defaultValue: 'sum', required: true },
      { key: 'field', label: 'Field (optional)', type: 'text', placeholder: 'price', helpText: 'Field to aggregate (leave empty to aggregate items directly)' },
      { key: 'groupBy', label: 'Group By (optional)', type: 'text', placeholder: 'category', helpText: 'Field to group by' },
    ],
  },
  {
    type: 'limit',
    label: 'Limit',
    category: 'data',
    icon: 'ListChecks',
    description: 'Limit array size',
    defaultConfig: { limit: 10 },
    configFields: [
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 10, required: true, helpText: 'Maximum number of items to return' },
    ],
  },
  {
    type: 'sort',
    label: 'Sort',
    category: 'data',
    icon: 'ArrowUpDown',
    description: 'Sort array items',
    defaultConfig: { direction: 'asc' },
    configFields: [
      { key: 'field', label: 'Field (optional)', type: 'text', placeholder: 'name', helpText: 'Field to sort by (leave empty to sort items directly)' },
      { key: 'direction', label: 'Direction', type: 'select', options: [
        { label: 'Ascending', value: 'asc' },
        { label: 'Descending', value: 'desc' },
      ], defaultValue: 'asc' },
      { key: 'type', label: 'Type', type: 'select', options: [
        { label: 'Auto', value: 'auto' },
        { label: 'String', value: 'string' },
        { label: 'Number', value: 'number' },
        { label: 'Date', value: 'date' },
      ], defaultValue: 'auto' },
    ],
  },
  {
    type: 'item_lists',
    label: 'Item Lists',
    category: 'data',
    icon: 'List',
    description: 'Convert object to list of key-value items',
    defaultConfig: {},
    configFields: [],
  },
  {
    type: 'merge_data',
    label: 'Merge Data',
    category: 'data',
    icon: 'Combine',
    description: 'Combine multiple inputs',
    defaultConfig: { mode: 'merge' },
    configFields: [
      { key: 'mode', label: 'Mode', type: 'select', options: [
        { label: 'Merge Objects', value: 'merge' },
        { label: 'Append to Array', value: 'append' },
        { label: 'Concatenate Arrays', value: 'concat' },
      ], defaultValue: 'merge' },
    ],
  },
  {
    type: 'set_variable',
    label: 'Set Variable',
    category: 'data',
    icon: 'Variable',
    description: 'Store value in variable',
    defaultConfig: {},
    configFields: [
      { key: 'name', label: 'Variable Name', type: 'text', placeholder: 'myVariable', required: true },
      { key: 'value', label: 'Value', type: 'textarea', placeholder: '{{input.data}}', required: true },
    ],
  },
  {
    type: 'json_parser',
    label: 'JSON Parser',
    category: 'data',
    icon: 'Braces',
    description: 'Parse/transform JSON',
    defaultConfig: { expression: '' },
    configFields: [
      { key: 'expression', label: 'JSONPath Expression', type: 'text', placeholder: '$.data.items[*]' },
    ],
  },
  {
    type: 'csv_processor',
    label: 'CSV Processor',
    category: 'data',
    icon: 'Table',
    description: 'Process CSV data',
    defaultConfig: { delimiter: ',' },
    configFields: [
      { key: 'delimiter', label: 'Delimiter', type: 'text', defaultValue: ',' },
      { key: 'hasHeader', label: 'Has Header Row', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'text_formatter',
    label: 'Text Formatter',
    category: 'data',
    icon: 'Type',
    description: 'Format text content',
    defaultConfig: { template: '' },
    configFields: [
      { key: 'template', label: 'Template', type: 'textarea', placeholder: 'Hello {{name}}!', required: true },
    ],
  },
  {
    type: 'google_sheets',
    label: 'Google Sheets',
    category: 'google',
    icon: 'Table',
    description: 'Read/write Google Sheets',
    defaultConfig: {
      operation: 'read',
      spreadsheetId: '',
      sheetName: '',
      range: '',
      outputFormat: 'json',
      allowWrite: false,
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'Read', value: 'read' },
          { label: 'Write', value: 'write' },
          { label: 'Append', value: 'append' },
          { label: 'Update', value: 'update' },
        ],
        defaultValue: 'read',
        required: true,
      },
      { 
        key: 'spreadsheetId', 
        label: 'Spreadsheet ID', 
        type: 'text', 
        placeholder: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms', 
        required: true,
        helpText: 'The ID from the Google Sheets URL (the long string between /d/ and /edit)',
      },
      { 
        key: 'sheetName', 
        label: 'Sheet Name (Tab)', 
        type: 'text', 
        placeholder: 'Sheet1',
        helpText: 'Leave empty to use the first sheet',
      },
      { 
        key: 'range', 
        label: 'Range (e.g., A1:D100)', 
        type: 'text', 
        placeholder: 'A1:D100',
        helpText: 'Leave empty to read all used cells. For write/update, specify the target range.',
      },
      { 
        key: 'outputFormat', 
        label: 'Output Format', 
        type: 'select', 
        options: [
          { label: 'JSON Array', value: 'json' },
          { label: 'Key-Value Pairs', value: 'keyvalue' },
          { label: 'Plain Text Table', value: 'text' },
        ],
        defaultValue: 'json',
        helpText: 'How to format the extracted data',
      },
      { 
        key: 'readDirection', 
        label: 'Read Direction', 
        type: 'select', 
        options: [
          { label: 'Row-wise (default)', value: 'rows' },
          { label: 'Column-wise', value: 'columns' },
        ],
        defaultValue: 'rows',
        helpText: 'How to read the data',
      },
      { 
        key: 'allowWrite', 
        label: 'Allow Write Access', 
        type: 'boolean', 
        defaultValue: false,
        helpText: '⚠️ Admin only: Enable write/update operations',
      },
      { 
        key: 'data', 
        label: 'Data to Write (JSON)', 
        type: 'json', 
        placeholder: '[["Name", "Email"], ["John", "john@example.com"]]',
        helpText: 'Required for write/append/update operations. Use JSON array format.',
      },
    ],
  },
  {
    type: 'google_doc',
    label: 'Google Doc',
    category: 'google',
    icon: 'FileText',
    description: 'Read/create/update Docs',
    defaultConfig: {
      operation: 'read',
      documentId: '',
      content: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'Read', value: 'read' },
          { label: 'Create', value: 'create' },
          { label: 'Update', value: 'update' },
        ],
        defaultValue: 'read',
        required: true,
      },
      { 
        key: 'documentId', 
        label: 'Document ID or URL', 
        type: 'text', 
        placeholder: 'https://docs.google.com/document/d/1a2b3c4d5e6f7g8h9i0j/edit or just 1a2b3c4d5e6f7g8h9i0j',
        helpText: 'Paste the full Google Docs URL (https://docs.google.com/document/d/DOCUMENT_ID/edit) or just the Document ID. Get it from the document URL. Leave empty for create operation.',
      },
      { 
        key: 'title', 
        label: 'Document Title', 
        type: 'text', 
        placeholder: 'My Document',
        helpText: 'Required for create operation',
      },
      { 
        key: 'content', 
        label: 'Content', 
        type: 'textarea', 
        placeholder: 'Document content...',
        helpText: 'Required for create/update operations',
      },
    ],
  },
  {
    type: 'google_drive',
    label: 'Google Drive',
    category: 'google',
    icon: 'Box',
    description: 'Manage Drive files',
    defaultConfig: {
      operation: 'list',
      folderId: '',
      fileName: '',
      fileContent: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'List Files', value: 'list' },
          { label: 'Upload File', value: 'upload' },
          { label: 'Download File', value: 'download' },
          { label: 'Delete File', value: 'delete' },
        ],
        defaultValue: 'list',
        required: true,
      },
      { 
        key: 'folderId', 
        label: 'Folder ID', 
        type: 'text', 
        placeholder: '1a2b3c4d5e6f7g8h9i0j',
        helpText: 'Folder ID for list operation. Leave empty for root folder.',
      },
      { 
        key: 'fileId', 
        label: 'File ID', 
        type: 'text', 
        placeholder: '1a2b3c4d5e6f7g8h9i0j',
        helpText: 'File ID for download/delete operations',
      },
      { 
        key: 'fileName', 
        label: 'File Name', 
        type: 'text', 
        placeholder: 'document.pdf',
        helpText: 'Required for upload operation',
      },
      { 
        key: 'fileContent', 
        label: 'File Content (Base64)', 
        type: 'textarea', 
        placeholder: 'Base64 encoded content...',
        helpText: 'Required for upload operation',
      },
    ],
  },
  {
    type: 'google_calendar',
    label: 'Google Calendar',
    category: 'google',
    icon: 'Calendar',
    description: 'Manage calendar events',
    defaultConfig: {
      operation: 'list',
      calendarId: 'primary',
      eventId: '',
      summary: '',
      startTime: '',
      endTime: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'List Events', value: 'list' },
          { label: 'Create Event', value: 'create' },
          { label: 'Update Event', value: 'update' },
          { label: 'Delete Event', value: 'delete' },
        ],
        defaultValue: 'list',
        required: true,
      },
      { 
        key: 'calendarId', 
        label: 'Calendar ID', 
        type: 'text', 
        placeholder: 'primary',
        defaultValue: 'primary',
        helpText: 'Calendar ID. Use "primary" for main calendar.',
      },
      { 
        key: 'eventId', 
        label: 'Event ID', 
        type: 'text', 
        placeholder: 'abc123def456',
        helpText: 'Required for update/delete operations',
      },
      { 
        key: 'summary', 
        label: 'Event Title', 
        type: 'text', 
        placeholder: 'Meeting with Team',
        helpText: 'Required for create/update operations',
      },
      { 
        key: 'startTime', 
        label: 'Start Time (ISO 8601)', 
        type: 'text', 
        placeholder: '2024-01-15T10:00:00Z',
        helpText: 'Required for create/update. Format: YYYY-MM-DDTHH:mm:ssZ',
      },
      { 
        key: 'endTime', 
        label: 'End Time (ISO 8601)', 
        type: 'text', 
        placeholder: '2024-01-15T11:00:00Z',
        helpText: 'Required for create/update. Format: YYYY-MM-DDTHH:mm:ssZ',
      },
      { 
        key: 'description', 
        label: 'Description', 
        type: 'textarea', 
        placeholder: 'Event description...',
      },
    ],
  },
  {
    type: 'google_gmail',
    label: 'Google Gmail',
    category: 'google',
    icon: 'Mail',
    description: 'Send/search Gmail',
    defaultConfig: {
      operation: 'send',
      to: '',
      subject: '',
      body: '',
      query: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'Send Email', value: 'send' },
          { label: 'List Messages', value: 'list' },
          { label: 'Get Message', value: 'get' },
          { label: 'Search Messages', value: 'search' },
        ],
        defaultValue: 'send',
        required: true,
      },
      { 
        key: 'to', 
        label: 'To', 
        type: 'text', 
        placeholder: 'recipient@example.com',
        helpText: 'Required for send operation',
      },
      { 
        key: 'subject', 
        label: 'Subject', 
        type: 'text', 
        placeholder: 'Email Subject',
        helpText: 'Required for send operation',
      },
      { 
        key: 'body', 
        label: 'Body', 
        type: 'textarea', 
        placeholder: 'Email body content...',
        helpText: 'Required for send operation',
      },
      { 
        key: 'messageId', 
        label: 'Message ID', 
        type: 'text', 
        placeholder: 'abc123def456',
        helpText: 'Required for get operation',
      },
      { 
        key: 'query', 
        label: 'Search Query', 
        type: 'text', 
        placeholder: 'from:example@gmail.com',
        helpText: 'Gmail search query for list/search operations',
      },
      { 
        key: 'maxResults', 
        label: 'Max Results', 
        type: 'number', 
        defaultValue: 10,
        helpText: 'Maximum number of messages to return',
      },
    ],
  },
  {
    type: 'google_bigquery',
    label: 'Google BigQuery',
    category: 'google',
    icon: 'DatabaseZap',
    description: 'Execute SQL queries',
    defaultConfig: {
      projectId: '',
      datasetId: '',
      query: '',
    },
    configFields: [
      { 
        key: 'projectId', 
        label: 'Project ID', 
        type: 'text', 
        placeholder: 'my-project-id',
        required: true,
        helpText: 'Google Cloud Project ID',
      },
      { 
        key: 'datasetId', 
        label: 'Dataset ID', 
        type: 'text', 
        placeholder: 'my_dataset',
        required: true,
        helpText: 'BigQuery Dataset ID',
      },
      { 
        key: 'query', 
        label: 'SQL Query', 
        type: 'textarea', 
        placeholder: 'SELECT * FROM `project.dataset.table` LIMIT 10',
        required: true,
        helpText: 'SQL query to execute',
      },
      { 
        key: 'useLegacySql', 
        label: 'Use Legacy SQL', 
        type: 'boolean', 
        defaultValue: false,
        helpText: 'Enable for legacy SQL syntax',
      },
    ],
  },
  {
    type: 'google_tasks',
    label: 'Google Tasks',
    category: 'google',
    icon: 'CheckCircle',
    description: 'Manage tasks',
    defaultConfig: {
      operation: 'list',
      taskListId: '',
      title: '',
      notes: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'List Tasks', value: 'list' },
          { label: 'Create Task', value: 'create' },
          { label: 'Update Task', value: 'update' },
          { label: 'Complete Task', value: 'complete' },
        ],
        defaultValue: 'list',
        required: true,
      },
      { 
        key: 'taskListId', 
        label: 'Task List ID', 
        type: 'text', 
        placeholder: '@default',
        defaultValue: '@default',
        helpText: 'Task list ID. Use "@default" for default list.',
      },
      { 
        key: 'taskId', 
        label: 'Task ID', 
        type: 'text', 
        placeholder: 'abc123def456',
        helpText: 'Required for update/complete operations',
      },
      { 
        key: 'title', 
        label: 'Task Title', 
        type: 'text', 
        placeholder: 'Complete project report',
        helpText: 'Required for create/update operations',
      },
      { 
        key: 'notes', 
        label: 'Notes', 
        type: 'textarea', 
        placeholder: 'Task notes...',
      },
      { 
        key: 'dueDate', 
        label: 'Due Date (ISO 8601)', 
        type: 'text', 
        placeholder: '2024-01-15T23:59:59Z',
        helpText: 'Due date in ISO 8601 format',
      },
    ],
  },
  {
    type: 'google_contacts',
    label: 'Google Contacts',
    category: 'google',
    icon: 'Users',
    description: 'Manage contacts',
    defaultConfig: {
      operation: 'list',
      contactId: '',
      name: '',
      email: '',
      phone: '',
    },
    configFields: [
      { 
        key: 'operation', 
        label: 'Operation', 
        type: 'select', 
        options: [
          { label: 'List Contacts', value: 'list' },
          { label: 'Create Contact', value: 'create' },
          { label: 'Update Contact', value: 'update' },
          { label: 'Delete Contact', value: 'delete' },
        ],
        defaultValue: 'list',
        required: true,
      },
      { 
        key: 'contactId', 
        label: 'Contact ID', 
        type: 'text', 
        placeholder: 'c1234567890',
        helpText: 'Required for update/delete operations',
      },
      { 
        key: 'name', 
        label: 'Name', 
        type: 'text', 
        placeholder: 'John Doe',
        helpText: 'Required for create/update operations',
      },
      { 
        key: 'email', 
        label: 'Email', 
        type: 'text', 
        placeholder: 'john@example.com',
        helpText: 'Required for create/update operations',
      },
      { 
        key: 'phone', 
        label: 'Phone', 
        type: 'text', 
        placeholder: '+1234567890',
      },
      { 
        key: 'maxResults', 
        label: 'Max Results', 
        type: 'number', 
        defaultValue: 100,
        helpText: 'Maximum number of contacts to return for list operation',
      },
    ],
  },

  // ============================================
  // 4. CODE & EXPRESSIONS NODES (4/4)
  // ============================================
  {
    type: 'javascript',
    label: 'JavaScript',
    category: 'data',
    icon: 'Code',
    description: 'Run custom code',
    defaultConfig: { code: 'return input;', timeout: 5000 },
    configFields: [
      { key: 'code', label: 'JavaScript Code', type: 'textarea', placeholder: 'return input;', required: true },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 5000, helpText: 'Maximum execution time' },
    ],
  },
  {
    type: 'function',
    label: 'Function',
    category: 'data',
    icon: 'Code2',
    description: 'Dataset-level code execution (operates on entire input)',
    defaultConfig: { code: 'return input;', timeout: 10000 },
    configFields: [
      { key: 'code', label: 'Function Code', type: 'textarea', placeholder: 'return input;', required: true, helpText: 'Code receives: input, data' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 10000 },
    ],
  },
  {
    type: 'function_item',
    label: 'Function Item',
    category: 'data',
    icon: 'Repeat',
    description: 'Per-item code execution (operates on each array item)',
    defaultConfig: { code: 'return item;', timeout: 5000 },
    configFields: [
      { key: 'code', label: 'Function Code', type: 'textarea', placeholder: 'return item;', required: true, helpText: 'Code receives: item, index, input' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 5000 },
    ],
  },
  {
    type: 'execute_command',
    label: 'Execute Command',
    category: 'data',
    icon: 'Terminal',
    description: 'Execute system command (disabled by default for security)',
    defaultConfig: { command: '', enabled: false, timeout: 30000 },
    configFields: [
      { key: 'command', label: 'Command', type: 'text', placeholder: 'echo "Hello"', required: true },
      { key: 'enabled', label: 'Enable Execution', type: 'boolean', defaultValue: false, helpText: '⚠️ WARNING: Command execution is disabled by default for security' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },

  // ============================================
  // 5. AI & ML NODES (8/8)
  // ============================================
  {
    type: 'openai_gpt',
    label: 'OpenAI GPT',
    category: 'ai',
    icon: 'Brain',
    description: 'Process with GPT models',
    defaultConfig: { model: 'gpt-4o', temperature: 0.7, memory: 10 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'sk-... (required)', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { label: 'GPT-4o', value: 'gpt-4o' },
        { label: 'GPT-4o Mini', value: 'gpt-4o-mini' },
        { label: 'GPT-4 Turbo', value: 'gpt-4-turbo' },
      ]},
      { key: 'prompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember (each turn = 1 user + 1 AI message)' },
    ],
  },
  {
    type: 'anthropic_claude',
    label: 'Anthropic Claude',
    category: 'ai',
    icon: 'Sparkles',
    description: 'Process with Claude models',
    defaultConfig: { model: 'claude-3-sonnet', temperature: 0.7, memory: 10 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'sk-ant-... (required)', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { label: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet' },
        { label: 'Claude 3 Opus', value: 'claude-3-opus' },
        { label: 'Claude 3 Haiku', value: 'claude-3-haiku' },
      ]},
      { key: 'prompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember (each turn = 1 user + 1 AI message)' },
    ],
  },
  {
    type: 'google_gemini',
    label: 'Google Gemini',
    category: 'ai',
    icon: 'Gem',
    description: 'Process with Gemini models',
    defaultConfig: { model: 'gemini-2.5-flash', temperature: 0.7, memory: 10 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'AIza... (required)', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
        { label: 'Gemini 2.5 Pro', value: 'gemini-2.5-pro' },
        { label: 'Gemini 2.5 Flash Lite', value: 'gemini-2.5-flash-lite' },
      ]},
      { key: 'prompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember (each turn = 1 user + 1 AI message)' },
    ],
  },
  {
    type: 'text_summarizer',
    label: 'Text Summarizer',
    category: 'ai',
    icon: 'FileText',
    description: 'Summarize text using AI',
    defaultConfig: { apiKey: '', memory: 10 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'sk-... (required)', required: true },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember (each turn = 1 user + 1 AI message)' },
    ],
  },
  {
    type: 'sentiment_analyzer',
    label: 'Sentiment Analysis',
    category: 'ai',
    icon: 'Heart',
    description: 'Analyze text sentiment',
    defaultConfig: { apiKey: '', memory: 10 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'sk-... (required)', required: true },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember (each turn = 1 user + 1 AI message)' },
    ],
  },
  {
    type: 'memory',
    label: 'Memory',
    category: 'ai',
    icon: 'Database',
    description: 'Store and retrieve conversation memory (Redis + Vector)',
    defaultConfig: {
      operation: 'store',
      memoryType: 'both',
      ttl: 3600,
      maxMessages: 100,
    },
    configFields: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        options: [
          { label: 'Store', value: 'store' },
          { label: 'Retrieve', value: 'retrieve' },
          { label: 'Clear', value: 'clear' },
          { label: 'Search', value: 'search' },
        ],
        required: true,
        helpText: 'What operation to perform on memory',
      },
      {
        key: 'memoryType',
        label: 'Memory Type',
        type: 'select',
        options: [
          { label: 'Short-term (Redis)', value: 'short' },
          { label: 'Long-term (Vector)', value: 'long' },
          { label: 'Both (Hybrid)', value: 'both' },
        ],
        defaultValue: 'both',
        helpText: 'Where to store/retrieve memory',
      },
      {
        key: 'ttl',
        label: 'TTL (seconds)',
        type: 'number',
        defaultValue: 3600,
        helpText: 'Time to live for short-term memory (Redis)',
      },
      {
        key: 'maxMessages',
        label: 'Max Messages',
        type: 'number',
        defaultValue: 100,
        helpText: 'Maximum messages to retrieve',
      },
    ],
  },
  {
    type: 'llm_chain',
    label: 'LLM Chain',
    category: 'ai',
    icon: 'Link',
    description: 'Chain multiple AI prompts together',
    defaultConfig: { steps: '[]', model: 'gpt-4o' },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'sk-... (required)', required: true },
      { key: 'model', label: 'Default Model', type: 'select', options: [
        { label: 'GPT-4o', value: 'gpt-4o' },
        { label: 'GPT-4o Mini', value: 'gpt-4o-mini' },
        { label: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet' },
        { label: 'Gemini 2.5 Flash', value: 'gemini-2.5-flash' },
      ], defaultValue: 'gpt-4o' },
      { key: 'steps', label: 'Chain Steps (JSON)', type: 'json', placeholder: '[{"prompt": "Step 1 prompt"}, {"prompt": "Step 2 prompt"}]', required: true, helpText: 'Array of steps, each with prompt and optional model' },
    ],
  },
  {
    type: 'azure_openai',
    label: 'Azure OpenAI',
    category: 'ai',
    icon: 'Brain',
    description: 'Process with Azure OpenAI models',
    defaultConfig: { endpoint: '', deploymentName: 'gpt-4', temperature: 0.7, apiVersion: '2024-02-15-preview' },
    configFields: [
      { key: 'endpoint', label: 'Azure Endpoint', type: 'text', placeholder: 'https://your-resource.openai.azure.com', required: true, helpText: 'Your Azure OpenAI endpoint URL' },
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your Azure API key (required)', required: true },
      { key: 'deploymentName', label: 'Deployment Name', type: 'text', placeholder: 'gpt-4', required: true, helpText: 'The deployment name you created in Azure' },
      { key: 'apiVersion', label: 'API Version', type: 'text', placeholder: '2024-02-15-preview', defaultValue: '2024-02-15-preview' },
      { key: 'prompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
      { key: 'memory', label: 'Memory', type: 'number', defaultValue: 10, placeholder: '10', helpText: 'Number of conversation turns to remember' },
    ],
  },
  {
    type: 'hugging_face',
    label: 'Hugging Face',
    category: 'ai',
    icon: 'Sparkles',
    description: 'Use Hugging Face Inference API models',
    defaultConfig: { model: '', task: 'text-generation' },
    configFields: [
      { key: 'apiKey', label: 'API Key (Hugging Face Token)', type: 'text', placeholder: 'hf_... (required)', required: true, helpText: 'Get your token from https://huggingface.co/settings/tokens' },
      { key: 'model', label: 'Model ID', type: 'text', placeholder: 'gpt2', required: true, helpText: 'Hugging Face model ID (e.g., gpt2, meta-llama/Llama-2-7b-chat-hf)' },
      { key: 'task', label: 'Task', type: 'select', options: [
        { label: 'Text Generation', value: 'text-generation' },
        { label: 'Text Classification', value: 'text-classification' },
        { label: 'Question Answering', value: 'question-answering' },
        { label: 'Summarization', value: 'summarization' },
        { label: 'Translation', value: 'translation' },
      ], defaultValue: 'text-generation' },
      { key: 'parameters', label: 'Parameters (JSON)', type: 'json', placeholder: '{"max_length": 100, "temperature": 0.7}' },
    ],
  },
  {
    type: 'cohere',
    label: 'Cohere',
    category: 'ai',
    icon: 'MessageSquare',
    description: 'Process with Cohere language models',
    defaultConfig: { model: 'command', temperature: 0.7 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your Cohere API key (required)', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { label: 'Command', value: 'command' },
        { label: 'Command Light', value: 'command-light' },
        { label: 'Command R', value: 'command-r' },
        { label: 'Command R+', value: 'command-r-plus' },
      ], defaultValue: 'command' },
      { key: 'prompt', label: 'Prompt', type: 'textarea', placeholder: 'Enter your prompt...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
    ],
  },
  {
    type: 'ollama',
    label: 'Ollama',
    category: 'ai',
    icon: 'Server',
    description: 'Run local LLMs via Ollama',
    defaultConfig: { serverUrl: 'http://localhost:11434', model: 'llama2' },
    configFields: [
      { key: 'serverUrl', label: 'Ollama Server URL', type: 'text', placeholder: 'http://localhost:11434', defaultValue: 'http://localhost:11434', required: true, helpText: 'URL of your Ollama server' },
      { key: 'model', label: 'Model Name', type: 'text', placeholder: 'llama2', defaultValue: 'llama2', required: true, helpText: 'Ollama model name (e.g., llama2, mistral, codellama)' },
      { key: 'prompt', label: 'Prompt', type: 'textarea', placeholder: 'Enter your prompt...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
    ],
  },
  {
    type: 'embeddings',
    label: 'Embeddings',
    category: 'ai',
    icon: 'Layers',
    description: 'Generate text embeddings/vectors',
    defaultConfig: { provider: 'openai', model: 'text-embedding-ada-002' },
    configFields: [
      { key: 'provider', label: 'Provider', type: 'select', options: [
        { label: 'OpenAI', value: 'openai' },
        { label: 'Google (Gemini)', value: 'gemini' },
      ], defaultValue: 'openai', required: true },
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your API key (required)', required: true },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'text-embedding-ada-002', defaultValue: 'text-embedding-ada-002', helpText: 'OpenAI: text-embedding-ada-002, text-embedding-3-small, text-embedding-3-large' },
      { key: 'text', label: 'Text to Embed', type: 'textarea', placeholder: 'Enter text to embed...', helpText: 'Leave empty to use input from previous node' },
      { key: 'dimensions', label: 'Dimensions (OpenAI)', type: 'number', helpText: 'Optional: For text-embedding-3 models (256, 512, 1024, etc.)' },
    ],
  },
  {
    type: 'vector_store',
    label: 'Vector Store',
    category: 'ai',
    icon: 'Database',
    description: 'Store and search vectors (embeddings)',
    defaultConfig: { provider: 'pinecone', operation: 'upsert' },
    configFields: [
      { key: 'provider', label: 'Provider', type: 'select', options: [
        { label: 'Pinecone', value: 'pinecone' },
        { label: 'Supabase (pgvector)', value: 'supabase' },
      ], defaultValue: 'pinecone', required: true },
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your API key (required)', required: true },
      { key: 'indexName', label: 'Index Name', type: 'text', placeholder: 'my-index', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Upsert', value: 'upsert' },
        { label: 'Query', value: 'query' },
        { label: 'Delete', value: 'delete' },
      ], defaultValue: 'upsert', required: true },
      { key: 'vectors', label: 'Vectors (JSON)', type: 'json', placeholder: '[{"id": "1", "values": [0.1, 0.2, ...], "metadata": {}}]', helpText: 'Required for upsert operation' },
      { key: 'queryVector', label: 'Query Vector (JSON)', type: 'json', placeholder: '{"vector": [0.1, 0.2, ...], "topK": 5}', helpText: 'Required for query operation' },
      { key: 'ids', label: 'IDs (JSON array)', type: 'json', placeholder: '["id1", "id2"]', helpText: 'Required for delete operation' },
    ],
  },
  {
    type: 'chat_model',
    label: 'Chat Model',
    category: 'ai',
    icon: 'MessageCircle',
    description: 'Unified interface for multiple LLM providers',
    defaultConfig: { provider: 'openai', model: 'gpt-4o', temperature: 0.7 },
    configFields: [
      { key: 'provider', label: 'Provider', type: 'select', options: [
        { label: 'OpenAI', value: 'openai' },
        { label: 'Anthropic Claude', value: 'anthropic' },
        { label: 'Google Gemini', value: 'gemini' },
        { label: 'Azure OpenAI', value: 'azure' },
      ], defaultValue: 'openai', required: true },
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your API key (required)', required: true },
      { key: 'model', label: 'Model', type: 'text', placeholder: 'gpt-4o', defaultValue: 'gpt-4o', required: true },
      { key: 'endpoint', label: 'Endpoint (Azure only)', type: 'text', placeholder: 'https://your-resource.openai.azure.com', helpText: 'Required for Azure provider' },
      { key: 'deploymentName', label: 'Deployment Name (Azure only)', type: 'text', placeholder: 'gpt-4', helpText: 'Required for Azure provider' },
      { key: 'prompt', label: 'System Prompt', type: 'textarea', placeholder: 'You are a helpful assistant...', required: true },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
    ],
  },
  {
    type: 'ai_agent',
    label: 'AI Agent',
    category: 'ai',
    icon: 'Bot',
    description: 'Autonomous AI agent with tool usage',
    defaultConfig: { model: 'gpt-4o', maxIterations: 5 },
    configFields: [
      { key: 'apiKey', label: 'API Key', type: 'text', placeholder: 'Your API key (required)', required: true },
      { key: 'model', label: 'Model', type: 'select', options: [
        { label: 'GPT-4o', value: 'gpt-4o' },
        { label: 'GPT-4o Mini', value: 'gpt-4o-mini' },
        { label: 'Claude 3.5 Sonnet', value: 'claude-3-5-sonnet' },
      ], defaultValue: 'gpt-4o', required: true },
      { key: 'prompt', label: 'Agent Prompt', type: 'textarea', placeholder: 'You are an AI agent that can use tools...', required: true },
      { key: 'tools', label: 'Tools (JSON)', type: 'json', placeholder: '[{"name": "search", "description": "Search the web", "parameters": {}}]', helpText: 'Array of available tools for the agent' },
      { key: 'maxIterations', label: 'Max Iterations', type: 'number', defaultValue: 5, helpText: 'Maximum number of reasoning steps' },
      { key: 'temperature', label: 'Temperature', type: 'number', defaultValue: 0.7 },
    ],
  },

  // ============================================
  // 6. HTTP & API NODES (3/3)
  // ============================================
  {
    type: 'http_request',
    label: 'HTTP Request',
    category: 'http_api',
    icon: 'Globe',
    description: 'Make HTTP API call',
    defaultConfig: { method: 'GET', url: '' },
    configFields: [
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://api.example.com/data', required: true },
      { key: 'method', label: 'Method', type: 'select', options: [
        { label: 'GET', value: 'GET' },
        { label: 'POST', value: 'POST' },
        { label: 'PUT', value: 'PUT' },
        { label: 'PATCH', value: 'PATCH' },
        { label: 'DELETE', value: 'DELETE' },
      ]},
      { key: 'headers', label: 'Headers (JSON)', type: 'json', placeholder: '{"Authorization": "Bearer token"}' },
      { key: 'body', label: 'Body (JSON)', type: 'json', placeholder: '{}' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    type: 'graphql',
    label: 'GraphQL',
    category: 'http_api',
    icon: 'Braces',
    description: 'Execute GraphQL query',
    defaultConfig: { url: '', query: '', operationName: '' },
    configFields: [
      { key: 'url', label: 'GraphQL Endpoint', type: 'text', placeholder: 'https://api.example.com/graphql', required: true },
      { key: 'query', label: 'Query', type: 'textarea', placeholder: 'query { user(id: 1) { name } }', required: true },
      { key: 'operationName', label: 'Operation Name', type: 'text', placeholder: 'GetUser' },
      { key: 'variables', label: 'Variables (JSON)', type: 'json', placeholder: '{"id": 1}' },
      { key: 'headers', label: 'Headers (JSON)', type: 'json', placeholder: '{"Authorization": "Bearer token"}' },
      { key: 'timeout', label: 'Timeout (ms)', type: 'number', defaultValue: 30000 },
    ],
  },
  {
    type: 'respond_to_webhook',
    label: 'Respond to Webhook',
    category: 'http_api',
    icon: 'Send',
    description: 'Send response to webhook caller',
    defaultConfig: { statusCode: 200, responseBody: '' },
    configFields: [
      { key: 'statusCode', label: 'Status Code', type: 'number', defaultValue: 200, required: true },
      { key: 'responseBody', label: 'Response Body (JSON)', type: 'json', placeholder: '{"message": "success"}' },
      { key: 'headers', label: 'Custom Headers (JSON)', type: 'json', placeholder: '{"Content-Type": "application/json"}' },
    ],
  },

  // ============================================
  // 7. OUTPUT/COMMUNICATION NODES (11/11)
  // ============================================
  {
    type: 'http_post',
    label: 'HTTP POST',
    category: 'output',
    icon: 'Send',
    description: 'Send HTTP POST request',
    defaultConfig: { url: '', method: 'POST' },
    configFields: [
      { key: 'url', label: 'URL', type: 'text', placeholder: 'https://api.example.com/webhook', required: true },
      { key: 'headers', label: 'Headers (JSON)', type: 'json', placeholder: '{}' },
      { key: 'bodyTemplate', label: 'Body Template', type: 'textarea', placeholder: '{"data": "{{input}}"}' },
    ],
  },
  {
    type: 'email_resend',
    label: 'Send Email (Resend)',
    category: 'output',
    icon: 'Mail',
    description: 'Send email via Resend',
    defaultConfig: {},
    configFields: [
      { key: 'to', label: 'To', type: 'text', placeholder: 'recipient@example.com', required: true },
      { key: 'from', label: 'From', type: 'text', placeholder: 'sender@yourdomain.com', required: true },
      { key: 'subject', label: 'Subject', type: 'text', placeholder: 'Workflow Notification', required: true },
      { key: 'body', label: 'Body (HTML allowed)', type: 'textarea', placeholder: '<h1>Hello!</h1><p>Your workflow completed.</p>', required: true },
      { key: 'replyTo', label: 'Reply-To', type: 'text', placeholder: 'reply@example.com' },
    ],
  },
  {
    type: 'slack_message',
    label: 'Slack Message',
    category: 'output',
    icon: 'MessageSquare',
    description: 'Send Slack notification',
    defaultConfig: {},
    configFields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text', placeholder: 'https://hooks.slack.com/services/...', required: true },
      { key: 'channel', label: 'Channel (optional)', type: 'text', placeholder: '#general' },
      { key: 'username', label: 'Bot Name', type: 'text', placeholder: 'Workflow Bot', defaultValue: 'CtrlChecks Bot' },
      { key: 'iconEmoji', label: 'Icon Emoji', type: 'text', placeholder: ':robot_face:', defaultValue: ':zap:' },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Workflow completed successfully!', required: true },
      { key: 'blocks', label: 'Blocks (JSON, optional)', type: 'json', placeholder: '[]' },
    ],
  },
  {
    type: 'slack_webhook',
    label: 'Slack Incoming Webhook',
    category: 'output',
    icon: 'Hash',
    description: 'Simple Slack webhook',
    defaultConfig: {},
    configFields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text', placeholder: 'https://hooks.slack.com/services/...', required: true },
      { key: 'text', label: 'Message Text', type: 'textarea', placeholder: 'Hello from CtrlChecks!', required: true },
    ],
  },
  {
    type: 'discord_webhook',
    label: 'Discord Webhook',
    category: 'output',
    icon: 'MessageCircle',
    description: 'Send Discord message',
    defaultConfig: {},
    configFields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text', placeholder: 'https://discord.com/api/webhooks/...', required: true },
      { key: 'content', label: 'Message', type: 'textarea', placeholder: 'Hello from CtrlChecks!', required: true },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'CtrlChecks Bot' },
      { key: 'avatarUrl', label: 'Avatar URL', type: 'text', placeholder: 'https://example.com/avatar.png' },
    ],
  },
  {
    type: 'microsoft_teams',
    label: 'Microsoft Teams',
    category: 'output',
    icon: 'MessageSquare',
    description: 'Send message to Microsoft Teams',
    defaultConfig: {},
    configFields: [
      { key: 'webhookUrl', label: 'Webhook URL', type: 'text', placeholder: 'https://outlook.office.com/webhook/...', required: true, helpText: 'Get from Teams channel Connectors' },
      { key: 'title', label: 'Title', type: 'text', placeholder: 'Workflow Notification', defaultValue: 'Workflow Notification' },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Your workflow completed successfully!', required: true },
    ],
  },
  {
    type: 'telegram',
    label: 'Telegram',
    category: 'output',
    icon: 'Send',
    description: 'Send message via Telegram Bot',
    defaultConfig: {},
    configFields: [
      { key: 'botToken', label: 'Bot Token', type: 'text', placeholder: '123456:ABC-DEF...', required: true, helpText: 'Get from @BotFather on Telegram' },
      { key: 'chatId', label: 'Chat ID', type: 'text', placeholder: '123456789', required: true, helpText: 'User or group chat ID' },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Hello from CtrlChecks!', required: true },
    ],
  },
  {
    type: 'whatsapp_cloud',
    label: 'WhatsApp Cloud API',
    category: 'output',
    icon: 'MessageCircle',
    description: 'Send message via WhatsApp Business API',
    defaultConfig: {},
    configFields: [
      { key: 'phoneNumberId', label: 'Phone Number ID', type: 'text', placeholder: '123456789012345', required: true },
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'EAAG...', required: true },
      { key: 'to', label: 'Recipient Number', type: 'text', placeholder: '1234567890', required: true, helpText: 'With country code, no +' },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Hello from CtrlChecks!', required: true },
    ],
  },
  {
    type: 'twilio',
    label: 'Twilio SMS',
    category: 'output',
    icon: 'Send',
    description: 'Send SMS via Twilio',
    defaultConfig: {},
    configFields: [
      { key: 'accountSid', label: 'Account SID', type: 'text', placeholder: 'AC...', required: true },
      { key: 'authToken', label: 'Auth Token', type: 'text', placeholder: '...', required: true },
      { key: 'from', label: 'From Number', type: 'text', placeholder: '+1234567890', required: true },
      { key: 'to', label: 'To Number', type: 'text', placeholder: '+1234567890', required: true },
      { key: 'message', label: 'Message', type: 'textarea', placeholder: 'Hello from CtrlChecks!', required: true },
    ],
  },
  {
    type: 'database_write',
    label: 'Database Write',
    category: 'database',
    icon: 'Database',
    description: 'Write to database',
    defaultConfig: { table: '' },
    configFields: [
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Insert', value: 'insert' },
        { label: 'Update', value: 'update' },
        { label: 'Upsert', value: 'upsert' },
        { label: 'Delete', value: 'delete' },
      ]},
      { key: 'data', label: 'Data Template', type: 'json', placeholder: '{"column": "{{input.value}}"}' },
      { key: 'matchColumn', label: 'Match Column (for update/upsert)', type: 'text', placeholder: 'id' },
    ],
  },
  {
    type: 'log_output',
    label: 'Log Output',
    category: 'output',
    icon: 'FileOutput',
    description: 'Log data for debugging',
    defaultConfig: {},
    configFields: [
      { key: 'message', label: 'Log Message', type: 'textarea', placeholder: 'Debug: {{input}}', required: true },
      { key: 'level', label: 'Log Level', type: 'select', options: [
        { label: 'Info', value: 'info' },
        { label: 'Warning', value: 'warn' },
        { label: 'Error', value: 'error' },
        { label: 'Debug', value: 'debug' },
      ], defaultValue: 'info' },
    ],
  },

  // ============================================
  // 8. DATABASE NODES (7/7)
  // ============================================
  {
    type: 'database_read',
    label: 'Database Read',
    category: 'database',
    icon: 'DatabaseZap',
    description: 'Read from database',
    defaultConfig: { table: '' },
    configFields: [
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', required: true },
      { key: 'columns', label: 'Columns', type: 'text', placeholder: '*', defaultValue: '*' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
      { key: 'orderBy', label: 'Order By', type: 'text', placeholder: 'created_at' },
      { key: 'ascending', label: 'Ascending', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'postgresql',
    label: 'PostgreSQL',
    category: 'database',
    icon: 'Database',
    description: 'Query PostgreSQL database',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select', required: true },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE id = 1', helpText: 'Required for raw SQL operation' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
      { key: 'orderBy', label: 'Order By', type: 'text', placeholder: 'created_at' },
      { key: 'ascending', label: 'Ascending', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'supabase',
    label: 'Supabase',
    category: 'database',
    icon: 'Database',
    description: 'Query Supabase database (PostgreSQL)',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select', required: true },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE id = 1', helpText: 'Required for raw SQL operation' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
      { key: 'orderBy', label: 'Order By', type: 'text', placeholder: 'created_at' },
      { key: 'ascending', label: 'Ascending', type: 'boolean', defaultValue: true },
    ],
  },
  {
    type: 'mysql',
    label: 'MySQL',
    category: 'database',
    icon: 'Database',
    description: 'Query MySQL database (requires connection setup)',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
      ], defaultValue: 'select' },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', required: true },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'mongodb',
    label: 'MongoDB',
    category: 'database',
    icon: 'Database',
    description: 'Query MongoDB database (requires connection setup)',
    defaultConfig: { operation: 'find' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Find', value: 'find' },
      ], defaultValue: 'find' },
      { key: 'collection', label: 'Collection Name', type: 'text', placeholder: 'my_collection', required: true },
      { key: 'query', label: 'Query (JSON)', type: 'json', placeholder: '{"field": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'redis',
    label: 'Redis',
    category: 'database',
    icon: 'Database',
    description: 'Redis operations (requires connection setup)',
    defaultConfig: { operation: 'get' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Get', value: 'get' },
        { label: 'Set', value: 'set' },
        { label: 'Delete', value: 'delete' },
      ], defaultValue: 'get' },
      { key: 'key', label: 'Key', type: 'text', placeholder: 'mykey', required: true },
      { key: 'value', label: 'Value', type: 'text', placeholder: 'myvalue', helpText: 'For set operation' },
      { key: 'ttl', label: 'TTL (seconds)', type: 'number', placeholder: '3600', helpText: 'For set operation' },
    ],
  },
  {
    type: 'mssql',
    label: 'Microsoft SQL Server',
    category: 'database',
    icon: 'Database',
    description: 'Query Microsoft SQL Server database',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'server', label: 'Server', type: 'text', placeholder: 'server.database.windows.net', required: true },
      { key: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'username', required: true },
      { key: 'password', label: 'Password', type: 'text', placeholder: 'password', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select' },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE id = 1', helpText: 'Required for raw SQL operation' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'sqlite',
    label: 'SQLite',
    category: 'database',
    icon: 'Database',
    description: 'Query SQLite database',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'databasePath', label: 'Database Path', type: 'text', placeholder: '/path/to/database.db', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select' },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE id = 1', helpText: 'Required for raw SQL operation' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'snowflake',
    label: 'Snowflake',
    category: 'database',
    icon: 'Database',
    description: 'Query Snowflake data warehouse',
    defaultConfig: { operation: 'select', warehouse: '', database: '', schema: 'PUBLIC' },
    configFields: [
      { key: 'account', label: 'Account', type: 'text', placeholder: 'xy12345', required: true, helpText: 'Snowflake account identifier' },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'username', required: true },
      { key: 'password', label: 'Password', type: 'text', placeholder: 'password', required: true },
      { key: 'warehouse', label: 'Warehouse', type: 'text', placeholder: 'COMPUTE_WH', required: true },
      { key: 'database', label: 'Database', type: 'text', placeholder: 'SNOWFLAKE_SAMPLE_DATA', required: true },
      { key: 'schema', label: 'Schema', type: 'text', placeholder: 'PUBLIC', defaultValue: 'PUBLIC' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select' },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE id = 1', helpText: 'Required for raw SQL operation' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },
  {
    type: 'timescaledb',
    label: 'TimescaleDB',
    category: 'database',
    icon: 'Database',
    description: 'Query TimescaleDB (time-series PostgreSQL)',
    defaultConfig: { operation: 'select' },
    configFields: [
      { key: 'host', label: 'Host', type: 'text', placeholder: 'localhost', required: true },
      { key: 'port', label: 'Port', type: 'number', defaultValue: 5432 },
      { key: 'database', label: 'Database', type: 'text', placeholder: 'mydb', required: true },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'postgres', required: true },
      { key: 'password', label: 'Password', type: 'text', placeholder: 'password', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Select', value: 'select' },
        { label: 'Raw SQL', value: 'query' },
      ], defaultValue: 'select' },
      { key: 'table', label: 'Table Name', type: 'text', placeholder: 'my_table', helpText: 'Required for select operation' },
      { key: 'query', label: 'SQL Query', type: 'textarea', placeholder: 'SELECT * FROM table WHERE time > NOW() - INTERVAL \'1 hour\'', helpText: 'Required for raw SQL operation' },
      { key: 'filters', label: 'Filters (JSON)', type: 'json', placeholder: '{"column": "value"}' },
      { key: 'limit', label: 'Limit', type: 'number', defaultValue: 100 },
    ],
  },

  // ============================================
  // 9. FILE OPERATIONS (4/4)
  // ============================================
  {
    type: 'read_binary_file',
    label: 'Read Binary File',
    category: 'storage',
    icon: 'FileText',
    description: 'Read file from filesystem',
    defaultConfig: { maxSize: 10485760 },
    configFields: [
      { key: 'filePath', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
      { key: 'maxSize', label: 'Max Size (bytes)', type: 'number', defaultValue: 10485760, helpText: '10MB default' },
    ],
  },
  {
    type: 'aws_s3',
    label: 'AWS S3',
    category: 'storage',
    icon: 'Cloud',
    description: 'Read or write files to/from AWS S3',
    defaultConfig: { operation: 'get', region: 'us-east-1' },
    configFields: [
      { key: 'accessKeyId', label: 'Access Key ID', type: 'text', placeholder: 'AKIA...', required: true },
      { key: 'secretAccessKey', label: 'Secret Access Key', type: 'text', placeholder: 'Your secret key', required: true },
      { key: 'region', label: 'Region', type: 'text', placeholder: 'us-east-1', defaultValue: 'us-east-1', required: true },
      { key: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Get Object', value: 'get' },
        { label: 'Put Object', value: 'put' },
        { label: 'List Objects', value: 'list' },
        { label: 'Delete Object', value: 'delete' },
      ], defaultValue: 'get', required: true },
      { key: 'key', label: 'Object Key (Path)', type: 'text', placeholder: 'path/to/file.txt', helpText: 'Required for get/put/delete operations' },
      { key: 'content', label: 'Content (for Put)', type: 'textarea', placeholder: 'File content or base64', helpText: 'Required for put operation' },
      { key: 'prefix', label: 'Prefix (for List)', type: 'text', placeholder: 'folder/', helpText: 'Optional prefix for list operation' },
    ],
  },
  {
    type: 'ftp',
    label: 'FTP',
    category: 'storage',
    icon: 'Folder',
    description: 'File Transfer Protocol operations',
    defaultConfig: { operation: 'get', port: 21 },
    configFields: [
      { key: 'host', label: 'Host', type: 'text', placeholder: 'ftp.example.com', required: true },
      { key: 'port', label: 'Port', type: 'number', defaultValue: 21 },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'username', required: true },
      { key: 'password', label: 'Password', type: 'text', placeholder: 'password', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Get File', value: 'get' },
        { label: 'Put File', value: 'put' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'get', required: true },
      { key: 'remotePath', label: 'Remote Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
      { key: 'content', label: 'Content (for Put)', type: 'textarea', placeholder: 'File content', helpText: 'Required for put operation' },
    ],
  },
  {
    type: 'sftp',
    label: 'SFTP',
    category: 'storage',
    icon: 'Lock',
    description: 'Secure File Transfer Protocol operations',
    defaultConfig: { operation: 'get', port: 22 },
    configFields: [
      { key: 'host', label: 'Host', type: 'text', placeholder: 'sftp.example.com', required: true },
      { key: 'port', label: 'Port', type: 'number', defaultValue: 22 },
      { key: 'username', label: 'Username', type: 'text', placeholder: 'username', required: true },
      { key: 'password', label: 'Password', type: 'text', placeholder: 'password', helpText: 'Use password or private key' },
      { key: 'privateKey', label: 'Private Key (SSH)', type: 'textarea', placeholder: '-----BEGIN RSA PRIVATE KEY-----', helpText: 'SSH private key (alternative to password)' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Get File', value: 'get' },
        { label: 'Put File', value: 'put' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'get', required: true },
      { key: 'remotePath', label: 'Remote Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
      { key: 'content', label: 'Content (for Put)', type: 'textarea', placeholder: 'File content', helpText: 'Required for put operation' },
    ],
  },
  {
    type: 'google_drive',
    label: 'Google Drive',
    category: 'storage',
    icon: 'Cloud',
    description: 'Read or write files to/from Google Drive',
    defaultConfig: { operation: 'read' },
    configFields: [
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'Your Google OAuth token', required: true, helpText: 'Google OAuth 2.0 access token' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Read File', value: 'read' },
        { label: 'Upload File', value: 'upload' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'read', required: true },
      { key: 'fileId', label: 'File ID', type: 'text', placeholder: '1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms', helpText: 'Google Drive file ID (for read/delete operations)' },
      { key: 'fileName', label: 'File Name (for Upload)', type: 'text', placeholder: 'document.txt', helpText: 'Required for upload operation' },
      { key: 'content', label: 'Content (for Upload)', type: 'textarea', placeholder: 'File content', helpText: 'Required for upload operation' },
      { key: 'folderId', label: 'Folder ID (for List)', type: 'text', placeholder: 'Folder ID', helpText: 'Optional: List files in specific folder' },
    ],
  },
  {
    type: 'dropbox',
    label: 'Dropbox',
    category: 'storage',
    icon: 'Cloud',
    description: 'Read or write files to/from Dropbox',
    defaultConfig: { operation: 'read' },
    configFields: [
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'Your Dropbox access token', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Download File', value: 'read' },
        { label: 'Upload File', value: 'upload' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'read', required: true },
      { key: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true, helpText: 'Dropbox file path' },
      { key: 'content', label: 'Content (for Upload)', type: 'textarea', placeholder: 'File content', helpText: 'Required for upload operation' },
    ],
  },
  {
    type: 'onedrive',
    label: 'OneDrive',
    category: 'storage',
    icon: 'Cloud',
    description: 'Read or write files to/from Microsoft OneDrive',
    defaultConfig: { operation: 'read' },
    configFields: [
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'Your Microsoft access token', required: true, helpText: 'Microsoft Graph API access token' },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Download File', value: 'read' },
        { label: 'Upload File', value: 'upload' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'read', required: true },
      { key: 'fileId', label: 'File ID', type: 'text', placeholder: 'File ID', helpText: 'OneDrive file ID (for read/delete operations)' },
      { key: 'path', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', helpText: 'OneDrive file path (alternative to file ID)' },
      { key: 'fileName', label: 'File Name (for Upload)', type: 'text', placeholder: 'document.txt', helpText: 'Required for upload operation' },
      { key: 'content', label: 'Content (for Upload)', type: 'textarea', placeholder: 'File content', helpText: 'Required for upload operation' },
    ],
  },
  {
    type: 'box',
    label: 'Box',
    category: 'storage',
    icon: 'Cloud',
    description: 'Read or write files to/from Box',
    defaultConfig: { operation: 'read' },
    configFields: [
      { key: 'accessToken', label: 'Access Token', type: 'text', placeholder: 'Your Box access token', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Download File', value: 'read' },
        { label: 'Upload File', value: 'upload' },
        { label: 'List Files', value: 'list' },
        { label: 'Delete File', value: 'delete' },
      ], defaultValue: 'read', required: true },
      { key: 'fileId', label: 'File ID', type: 'text', placeholder: 'File ID', helpText: 'Box file ID (for read/delete operations)' },
      { key: 'fileName', label: 'File Name (for Upload)', type: 'text', placeholder: 'document.txt', helpText: 'Required for upload operation' },
      { key: 'content', label: 'Content (for Upload)', type: 'textarea', placeholder: 'File content', helpText: 'Required for upload operation' },
      { key: 'folderId', label: 'Folder ID', type: 'text', placeholder: '0', defaultValue: '0', helpText: 'Folder ID for upload/list operations (0 = root)' },
    ],
  },
  {
    type: 'minio',
    label: 'MinIO',
    category: 'storage',
    icon: 'Database',
    description: 'Read or write files to/from MinIO object storage',
    defaultConfig: { operation: 'get', port: 9000 },
    configFields: [
      { key: 'endpoint', label: 'Endpoint', type: 'text', placeholder: 'localhost:9000', required: true },
      { key: 'accessKey', label: 'Access Key', type: 'text', placeholder: 'minioadmin', required: true },
      { key: 'secretKey', label: 'Secret Key', type: 'text', placeholder: 'minioadmin', required: true },
      { key: 'bucket', label: 'Bucket Name', type: 'text', placeholder: 'my-bucket', required: true },
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Get Object', value: 'get' },
        { label: 'Put Object', value: 'put' },
        { label: 'List Objects', value: 'list' },
        { label: 'Delete Object', value: 'delete' },
      ], defaultValue: 'get', required: true },
      { key: 'key', label: 'Object Key (Path)', type: 'text', placeholder: 'path/to/file.txt', helpText: 'Required for get/put/delete operations' },
      { key: 'content', label: 'Content (for Put)', type: 'textarea', placeholder: 'File content or base64', helpText: 'Required for put operation' },
      { key: 'useSSL', label: 'Use SSL', type: 'boolean', defaultValue: false },
    ],
  },
  {
    type: 'write_binary_file',
    label: 'Write Binary File',
    category: 'storage',
    icon: 'FileOutput',
    description: 'Write file to filesystem',
    defaultConfig: {},
    configFields: [
      { key: 'filePath', label: 'File Path', type: 'text', placeholder: '/path/to/file.txt', required: true },
      { key: 'content', label: 'Content (Base64)', type: 'textarea', placeholder: 'SGVsbG8gV29ybGQ=', required: true, helpText: 'Base64 encoded content' },
    ],
  },
  {
    type: 'rss_feed_read',
    label: 'RSS Feed Read',
    category: 'data',
    icon: 'Rss',
    description: 'Read and parse RSS feed',
    defaultConfig: { maxItems: 10 },
    configFields: [
      { key: 'feedUrl', label: 'Feed URL', type: 'text', placeholder: 'https://example.com/feed.xml', required: true },
      { key: 'maxItems', label: 'Max Items', type: 'number', defaultValue: 10 },
    ],
  },

  // ============================================
  // 10. UTILITY NODES (6/6)
  // ============================================
  {
    type: 'date_time',
    label: 'Date & Time',
    category: 'data',
    icon: 'Clock',
    description: 'Manipulate dates and times',
    defaultConfig: { operation: 'format' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Format', value: 'format' },
        { label: 'Add', value: 'add' },
        { label: 'Subtract', value: 'subtract' },
        { label: 'Difference', value: 'diff' },
        { label: 'Now', value: 'now' },
      ], defaultValue: 'format', required: true },
      { key: 'date', label: 'Date (ISO)', type: 'text', placeholder: '2024-01-15T10:30:00Z', helpText: 'Leave empty for current date' },
      { key: 'format', label: 'Format', type: 'select', options: [
        { label: 'ISO', value: 'ISO' },
        { label: 'Timestamp', value: 'timestamp' },
        { label: 'Custom', value: 'custom' },
      ], defaultValue: 'ISO' },
      { key: 'value', label: 'Value', type: 'number', placeholder: '1', helpText: 'For add/subtract operations' },
      { key: 'unit', label: 'Unit', type: 'select', options: [
        { label: 'Seconds', value: 'seconds' },
        { label: 'Minutes', value: 'minutes' },
        { label: 'Hours', value: 'hours' },
        { label: 'Days', value: 'days' },
        { label: 'Weeks', value: 'weeks' },
        { label: 'Months', value: 'months' },
        { label: 'Years', value: 'years' },
      ], defaultValue: 'days' },
    ],
  },
  {
    type: 'math',
    label: 'Math',
    category: 'data',
    icon: 'Calculator',
    description: 'Mathematical operations',
    defaultConfig: { operation: 'add' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Add', value: 'add' },
        { label: 'Subtract', value: 'subtract' },
        { label: 'Multiply', value: 'multiply' },
        { label: 'Divide', value: 'divide' },
        { label: 'Modulo', value: 'modulo' },
        { label: 'Power', value: 'power' },
        { label: 'Square Root', value: 'sqrt' },
        { label: 'Absolute', value: 'abs' },
        { label: 'Round', value: 'round' },
        { label: 'Floor', value: 'floor' },
        { label: 'Ceiling', value: 'ceil' },
        { label: 'Minimum', value: 'min' },
        { label: 'Maximum', value: 'max' },
      ], defaultValue: 'add', required: true },
      { key: 'value1', label: 'Value 1', type: 'text', placeholder: '0 or {{value1}}', helpText: 'Supports template expressions like {{value1}}' },
      { key: 'value2', label: 'Value 2', type: 'text', placeholder: '0 or {{value2}}', helpText: 'Not needed for single-value operations. Supports template expressions.' },
    ],
  },
  {
    type: 'crypto',
    label: 'Crypto',
    category: 'data',
    icon: 'Lock',
    description: 'Cryptographic operations',
    defaultConfig: { operation: 'hash' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Hash', value: 'hash' },
        { label: 'Encode Base64', value: 'encode_base64' },
        { label: 'Decode Base64', value: 'decode_base64' },
        { label: 'Generate UUID', value: 'uuid' },
        { label: 'Random String', value: 'random_string' },
      ], defaultValue: 'hash', required: true },
      { key: 'algorithm', label: 'Hash Algorithm', type: 'select', options: [
        { label: 'SHA-256', value: 'sha256' },
        { label: 'SHA-512', value: 'sha512' },
        { label: 'SHA-1', value: 'sha1' },
      ], defaultValue: 'sha256', helpText: 'For hash operation' },
      { key: 'length', label: 'Length', type: 'number', defaultValue: 16, helpText: 'For random string' },
      { key: 'charset', label: 'Character Set', type: 'text', defaultValue: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', helpText: 'For random string' },
    ],
  },
  {
    type: 'html_extract',
    label: 'HTML Extract',
    category: 'data',
    icon: 'Code',
    description: 'Extract content from HTML',
    defaultConfig: {},
    configFields: [
      { key: 'html', label: 'HTML Content', type: 'textarea', placeholder: '<html>...</html>', helpText: 'Leave empty to use input' },
      { key: 'selector', label: 'CSS Selector/Tag', type: 'text', placeholder: 'div, p, h1', helpText: 'Tag name or selector to extract' },
    ],
  },
  {
    type: 'xml',
    label: 'XML',
    category: 'data',
    icon: 'FileText',
    description: 'Parse and extract from XML',
    defaultConfig: { operation: 'parse' },
    configFields: [
      { key: 'operation', label: 'Operation', type: 'select', options: [
        { label: 'Parse', value: 'parse' },
        { label: 'Extract', value: 'extract' },
      ], defaultValue: 'parse' },
      { key: 'xml', label: 'XML Content', type: 'textarea', placeholder: '<root><item>value</item></root>', helpText: 'Leave empty to use input' },
      { key: 'xpath', label: 'XPath Expression', type: 'text', placeholder: '/root/item', helpText: 'For extract operation' },
    ],
  },
];

export const getNodesByCategory = (category: NodeCategory) => 
  NODE_TYPES.filter((node) => node.category === category);

export const getNodeDefinition = (type: string) => 
  NODE_TYPES.find((node) => node.type === type);
